package com.ushan.SocialMedia.enums;

public enum NotificationType {
    FRIENDSHIP_REQUEST,
    NEW_FOLLOWER,
    LIKED_ON_POST,
    COMMENTED_ON_POST,
    FRIEND_NEW_POST,
    MENTIONED_IN_COMMENT,
    TAGGED_IN_POST,
    MENTIONED_IN_POST,
    INVITE_TO_PAGE,
    INVITE_TO_GROUP,
    FRIEND_MESSAGE
}